# Generated by Django 5.2.8 on 2025-12-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bonus_bitcoins',
            field=models.IntegerField(default=0),
        ),
    ]
