# Generated by Django 5.2.8 on 2025-12-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_useraccount_bonus_bitcoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_slug', models.SlugField()),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('seat_code', models.CharField(max_length=5)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookingapp.useraccount')),
            ],
            options={
                'unique_together': {('movie_slug', 'show_date', 'show_time', 'seat_code')},
            },
        ),
    ]
