# Generated by Django 5.2.8 on 2025-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_seatbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatbooking',
            old_name='seat_code',
            new_name='seat_label',
        ),
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='movie_slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='show_time',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='user',
        ),
    ]
