# Generated by Django 5.2.8 on 2025-12-10 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_rename_seat_code_seatbooking_seat_label_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together={('show_date', 'seat_label')},
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='movie_slug',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='show_time',
        ),
    ]
