# Generated by Django 5.2.8 on 2025-12-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_alter_seatbooking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='seat_label',
            field=models.CharField(max_length=10),
        ),
    ]
