# Generated by Django 5.2.8 on 2025-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_alter_seatbooking_booked_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='movie_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together={('movie_name', 'show_date', 'seat_label')},
        ),
    ]
